// Fallback in-memory data store in case MongoDB Atlas SSL/Network is unreachable
export const memoryData = {
  categories: [
    { _id: 'cat1', name: 'Popular', slug: 'popular', icon: 'Flame', sortOrder: 1 },
    { _id: 'cat2', name: 'Parotta', slug: 'parotta', icon: 'Disc', sortOrder: 2 },
    { _id: 'cat3', name: 'Chicken', slug: 'chicken', icon: 'Drumstick', sortOrder: 3 },
    { _id: 'cat4', name: 'Biryani', slug: 'biryani', icon: 'Bowl', sortOrder: 4 },
    { _id: 'cat5', name: 'Rice & Noodles', slug: 'rice-noodles', icon: 'Utensils', sortOrder: 5 },
    { _id: 'cat6', name: 'Egg', slug: 'egg', icon: 'Egg', sortOrder: 6 },
    { _id: 'cat7', name: 'Dosa / Tiffin', slug: 'dosa', icon: 'CookingPot', sortOrder: 7 },
    { _id: 'cat8', name: 'Veg', slug: 'veg', icon: 'Leaf', sortOrder: 8 },
    { _id: 'cat9', name: 'Beverages', slug: 'beverages', icon: 'Coffee', sortOrder: 9 },
  ],
  menuItems: [
    {
      _id: 'm1',
      name: 'Bun Parotta',
      tamilName: 'பன் பரோட்டா',
      category: 'Parotta',
      price: 35,
      description: 'Soft, fluffy and multi-layered Tamil Nadu style bun parotta served with spicy chicken salna.',
      imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: true,
      rating: 4.9,
      preparationTime: '5-10 mins',
      tags: ['Must Try', 'Signature', 'Chef Special'],
      quickBillKey: 1,
      orderCount: 480
    },
    {
      _id: 'm2',
      name: 'Nool Parotta',
      tamilName: 'நூல் பரோட்டா',
      category: 'Parotta',
      price: 40,
      description: 'Thread-like layered parotta crafted to crispy perfection, soft and flaky inside.',
      imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: false,
      rating: 4.8,
      preparationTime: '8-12 mins',
      tags: ['Crispy', 'Popular'],
      quickBillKey: null,
      orderCount: 310
    },
    {
      _id: 'm3',
      name: 'Elai Parotta',
      tamilName: 'இலை பரோட்டா',
      category: 'Parotta',
      price: 130,
      description: 'Bun parotta smothered in thick chicken chukka gravy, wrapped in fresh banana leaf and slow steamed.',
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: true,
      rating: 5.0,
      preparationTime: '12-15 mins',
      tags: ['Banana Leaf', 'Signature'],
      quickBillKey: null,
      orderCount: 290
    },
    {
      _id: 'm4',
      name: 'Chicken Kothu Parotta',
      tamilName: 'சிக்கன் கொத்து பரோட்டா',
      category: 'Parotta',
      price: 120,
      description: 'Shredded bun parotta tossed on hot iron tawa with spiced chicken pieces, scrambled eggs, and curry leaves.',
      imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: false,
      rating: 4.9,
      preparationTime: '10-15 mins',
      tags: ['Spicy', 'Street Style'],
      quickBillKey: null,
      orderCount: 415
    },
    {
      _id: 'm5',
      name: 'Chicken Biryani',
      tamilName: 'சிக்கன் பிரியாணி',
      category: 'Biryani',
      price: 150,
      description: 'Aromatic Seeraga Samba rice cooked with tender chicken pieces, ghee, and authentic Kovai spices.',
      imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: true,
      rating: 4.9,
      preparationTime: '5 mins',
      tags: ['Best Seller', 'Seeraga Samba'],
      quickBillKey: 2,
      orderCount: 520
    },
    {
      _id: 'm6',
      name: 'Pepper Chicken Gravy',
      tamilName: 'பெப்பர் சிக்கன் கிரேவி',
      category: 'Chicken',
      price: 180,
      description: 'Tender chicken braised in freshly ground black pepper, small shallots, and curry leaves gravy.',
      imageUrl: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: true,
      rating: 4.9,
      preparationTime: '12-15 mins',
      tags: ['Pepper Hot', 'Classic'],
      quickBillKey: 5,
      orderCount: 380
    },
    {
      _id: 'm7',
      name: 'Chicken 65',
      tamilName: 'சிக்கன் 65',
      category: 'Chicken',
      price: 150,
      description: 'Crispy deep fried boneless chicken marinated in red chilli paste, ginger-garlic, and curry leaves.',
      imageUrl: 'https://images.unsplash.com/photo-1610057099431-d73a1c9d2f2f?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: false,
      rating: 4.9,
      preparationTime: '8-10 mins',
      tags: ['Starter', 'Favorite'],
      quickBillKey: null,
      orderCount: 460
    },
    {
      _id: 'm8',
      name: 'Chicken Rice',
      tamilName: 'சிக்கன் ரைஸ்',
      category: 'Rice & Noodles',
      price: 120,
      description: 'Wok-tossed Indo-Chinese rice with marinated chicken bits, scrambled eggs, and spring onion.',
      imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: false,
      rating: 4.7,
      preparationTime: '10 mins',
      tags: ['Fast Food'],
      quickBillKey: 3,
      orderCount: 390
    },
    {
      _id: 'm9',
      name: 'Egg Rice',
      tamilName: 'முட்டை ரைஸ்',
      category: 'Rice & Noodles',
      price: 95,
      description: 'Wok-fried rice blended with fluffy eggs, white pepper, and coriander leaves.',
      imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
      isVeg: false,
      isAvailable: true,
      isPopular: true,
      isSpecial: false,
      rating: 4.6,
      preparationTime: '8 mins',
      tags: ['Fast Food'],
      quickBillKey: 4,
      orderCount: 350
    },
    {
      _id: 'm10',
      name: 'Ghee Roast Dosa',
      tamilName: 'நெய் ரோஸ்ட் தோசை',
      category: 'Dosa / Tiffin',
      price: 85,
      description: 'Golden paper crispy crepe roasted in pure desi ghee, served with coconut & kara chutney.',
      imageUrl: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=800&q=80',
      isVeg: true,
      isAvailable: true,
      isPopular: true,
      isSpecial: false,
      rating: 4.9,
      preparationTime: '8 mins',
      tags: ['Pure Veg', 'Ghee Flavor'],
      quickBillKey: null,
      orderCount: 310
    },
    {
      _id: 'm11',
      name: 'Madurai Jigarthanda',
      tamilName: 'மதுரை ஜிகர்தண்டா',
      category: 'Beverages',
      price: 65,
      description: 'Traditional cooling dessert drink crafted with almond gum (badam pisin), nannari syrup, and cream ice cream.',
      imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=800&q=80',
      isVeg: true,
      isAvailable: true,
      isPopular: true,
      isSpecial: true,
      rating: 5.0,
      preparationTime: '3 mins',
      tags: ['Famous Cooling Drink'],
      quickBillKey: null,
      orderCount: 380
    }
  ],
  orders: []
};
